name: "rezervo-web"
services:
  rezervo-web:
    container_name: rezervo-web
    build:
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - .env.local:/app/.env.local:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
